import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="h-16 flex items-center">
          <a href="/">
            <span className='font-sans text-2xl pl-4'>
              Hidden Hues
            </span>
          </a>
        </nav>
        <main>
          {children}
        </main>
        <footer className="h-20">

        </footer>
      </body>
    </html>
  )
}
